Repository dnd-side-project/dnd-11th-9-frontend, pull requests merged in 2024-08, with the labels that each got.

#8 Chore/#7 router setting
  app.json
  app/(app)/_layout.tsx
  app/(app)/alarm/_layout.tsx
  app/(app)/alarm/index.tsx
  app/(app)/index.tsx
  app/(app)/my/_layout.tsx
  app/(app)/my/cancel-account.tsx
  app/(app)/my/index.tsx
  app/(app)/my/profile.tsx
  app/(app)/project/_layout.tsx
  app/(app)/project/create.tsx
  app/(app)/project/delete.tsx
  app/(app)/project/index.tsx
  app/(app)/review/_layout.tsx
  app/(app)/review/create.tsx
  app/(app)/review/delete.tsx
  app/(app)/review/index.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/explore.tsx
  app/(tabs)/index.tsx
  app/+html.tsx
  app/+not-found.tsx
  app/_layout.tsx
  app/on-boarding.tsx
  app/sign-in.tsx
  docs/code-convention.md
  docs/git-convention.md
  docs/libs.md
  docs/routing.md
  package.json
  src/components/common/customButton/CustomButton.stories.tsx
  src/components/common/customButton/index.tsx
  src/components/common/icon/Icon.stories.tsx
  src/components/common/icon/index.tsx
  src/components/common/typography/Typography.stories.tsx
  src/components/common/typography/index.tsx
  src/constants/index.ts
  src/constants/navigations.ts
  src/constants/siteUrls.ts
  src/constants/storageKeys.ts
  src/hooks/useStorageState.ts
  src/store/index.ts
  src/store/useSession.tsx
  src/test/Typography.test.tsx
  yarn.lock
Labels: ⚙️Chore, ⚡Feat

#10 Chore/#9 github auto-assign을 추가합니다.
  .github/auto_assign.yml
Labels: ⚙️Chore

#13 Chore/#12 Stylelint 설정을 추가합니다.
  .husky/pre-commit
  .stylelintrc.json
  app/(app)/_layout.tsx
  app/_layout.tsx
  package.json
  src/components/common/customButton/index.tsx
  yarn.lock
Labels: ⚙️Chore

#18 Chore/#17 expo 테스트 환경 세팅을 추가합니다.
  .gitignore
  .husky/pre-push
  app/_layout.tsx
  docs/typescript.md
  package.json
  src/components/common/customButton/index.tsx
  src/components/common/provider/index.tsx
  src/hooks/index.ts
  src/hooks/useAppOpen.ts
  src/hooks/useStorageState.ts
  src/test/Typography.test.tsx
  src/test/__snapshots__/ThemedText.test.tsx.snap
  src/test/__snapshots__/Typography.test.tsx.snap
  src/types/index.d.ts
  src/utils/getSize.ts
  src/utils/index.ts
  src/utils/render.tsx
  tsconfig.json
  yarn.lock
Labels: ⚙️Chore, ⚡Feat

#21 Feat/#4 폰트 경량화 및 Typography 컴포넌트를 추가합니다.
  .github/workflows/chromatic.yml
  .storybook/main.ts
  .storybook/preview.tsx
  app.json
  app/(app)/_layout.tsx
  app/(app)/alarm/index.tsx
  app/(app)/my/cancel-account.tsx
  app/(app)/my/index.tsx
  app/(app)/my/profile.tsx
  app/(app)/project/create.tsx
  app/(app)/project/delete.tsx
  app/(app)/project/index.tsx
  app/(app)/review/create.tsx
  app/(app)/review/delete.tsx
  app/(app)/review/index.tsx
  app/_layout.tsx
  assets/fonts/Pretendard-Black.otf
  assets/fonts/Pretendard-Bold.otf
  assets/fonts/Pretendard-ExtraBold.otf
  assets/fonts/Pretendard-ExtraLight.otf
  assets/fonts/Pretendard-Light.otf
  assets/fonts/Pretendard-Medium.otf
  assets/fonts/Pretendard-Regular.otf
  assets/fonts/Pretendard-SemiBold.otf
  assets/fonts/Pretendard-Thin.otf
  package.json
  src/components/common/customButton/CustomButton.stories.tsx
  src/components/common/customButton/index.tsx
  src/components/common/provider/index.tsx
  src/components/common/typography/Typography.stories.tsx
  src/components/common/typography/index.tsx
  src/hooks/useAppOpen.ts
  src/styles/theme.ts
  src/test/Typography.test.tsx
  src/test/__snapshots__/Typography.test.tsx.snap
  yarn.lock
Labels: Feat, Storybook

#23 Feat/#4 공용 버튼 컴포넌트를 추가하였습니다.
  .github/workflows/chromatic.yml
  .stylelintrc.json
  src/components/common/button/outlineButton/OultLineButton.stories.tsx
  src/components/common/button/outlineButton/index.tsx
  src/components/common/button/primaryButton/PrimaryButton.stories.tsx
  src/components/common/button/primaryButton/index.tsx
  src/components/common/customButton/CustomButton.stories.tsx
  src/components/common/customButton/index.tsx
  src/components/common/typography/index.tsx
  src/styles/common.ts
Labels: Feat, Storybook

#24 Chore/#1 chromatic deploy 조건을 수정합니다.
  .github/workflows/chromatic-deploy.yml
  .github/workflows/chromatic.yml
Labels: Chore, Storybook
