Repository dnd-side-project/dnd-11th-9-frontend, pull requests merged in 2024-10, with the labels that each got.

#76 Feat/#60 리뷰 카테고리 선택화면을 추가합니다.
  app/(app)/_layout.tsx
  app/(app)/project/[id]/detail/index.tsx
  app/(app)/project/[id]/detail/style.ts
  app/(app)/project/[id]/review/_layout.tsx
  app/(app)/project/[id]/review/create.tsx
  app/(app)/project/[id]/review/index.tsx
  app/(app)/project/_layout.tsx
  app/(app)/review/_layout.tsx
  app/(app)/review/create.tsx
  app/(app)/review/delete.tsx
  app/(app)/review/index.tsx
  src/components/common/icon/fire-svg.tsx
  src/components/onboarding/OnboardingSection/index.tsx
  src/components/project/ProjectDetail/index.tsx
  src/components/project/ProjectItem/index.tsx
  src/components/questionnaire/QuestionnaireCheckList/index.tsx
  src/components/questionnaire/QuestionnaireCheckList/style.ts
  src/components/questionnaire/SelectCategoryChipList/index.tsx
  src/components/questionnaire/SelectCategoryChipList/style.ts
  src/components/questionnaire/category/index.tsx
  src/components/questionnaire/category/style.ts
  src/components/review/Tag/index.tsx
  src/components/review/Tag/style.ts
  src/constants/navigations.ts
  src/constants/siteUrls.ts
  src/styles/category.ts
  src/styles/tag.ts
Labels: ⚡Feat, 🚧Refactor

#78 Fix/#77 ios에서 적용한 스타일과 다르게 보이는 현상을 수정합니다.
  app/(app)/index.tsx
  app/(app)/project/[id]/review/create.tsx
  app/(beforeLogin)/oauth2/authorization/login.tsx
  app/(beforeLogin)/oauth2/authorization/style.ts
  app/(beforeLogin)/sign-in.styles.tsx
  app/(beforeLogin)/sign-in.tsx
  src/components/onboarding/OnboardingScreen/index.tsx
  src/components/onboarding/OnboardingSection/index.tsx
  src/components/onboarding/OnboardingSection/style.ts
  src/components/project/ProjectDetail/style.ts
  src/components/questionnaire/QuestionnaireCheckList/style.ts
  src/components/questionnaire/QuestionnaireCheckListSkeleton/index.tsx
  src/components/sign-in/LogoSection.styles.tsx
  src/components/sign-in/LogoSection.tsx
Labels: 🔨Fix

#74 Feat/#40 마이페이지를 추가합니다.
  app/(app)/my/_layout.tsx
  app/(app)/my/cancel-account.tsx
  app/(app)/my/index.tsx
  app/(app)/my/job.tsx
  app/(app)/my/policy.tsx
  app/(app)/my/profile.tsx
  src/components/common/toggle/Toggle.stories.tsx
  src/components/common/toggle/index.tsx
  src/components/mypage/MenuList.style.ts
  src/components/mypage/MenuList.tsx
  src/components/mypage/Profile.style.ts
  src/components/mypage/Profile.tsx
  src/constants/navigations.ts
Labels: ⚡Feat, 📕Storybook

#80 Refactor/#22 onboarding 화면을 이미지로 변경합니다.
  assets/images/onboarding/0.png
  assets/images/onboarding/1.png
  assets/images/onboarding/2.png
  assets/images/onboarding/3.png
  src/components/home/BusinessCard/index.tsx
  src/components/home/BusinessCard/style.ts
  src/components/onboarding/OnboardingScreen/OnboardingScreen.stories.tsx
  src/components/onboarding/OnboardingScreen/index.tsx
  src/components/onboarding/OnboardingSection/index.tsx
  src/components/onboarding/OnboardingSection/style.ts
  src/components/questionnaire/QuestionnaireCheckList/index.tsx
  src/components/questionnaire/QuestionnaireCheckList/style.ts
  src/components/questionnaire/QuestionnaireCheckListSkeleton/index.tsx
  src/components/questionnaire/category/index.tsx
Labels: 📕Storybook, 🚧Refactor

#82 Fix/#77 root layout navigation error
  app/(beforeLogin)/oauth2/authorization/login.tsx
  app/(beforeLogin)/sign-in.tsx
  src/components/home/BusinessCard/BusinessCard.stories.tsx
  src/store/useSession.tsx
Labels: 📕Storybook, 🔨Fix

#84 Feat/#2 CustomHeader를 추가합니다.
  src/components/common/custom-header/CustomHeader.stories.tsx
  src/components/common/custom-header/index.tsx
  src/components/common/custom-header/style.ts
Labels: ⚡Feat, 📕Storybook

#83 Feat/#60 설문지 작성 기능을 추가합니다.
  app/(app)/_layout.tsx
  app/(app)/project/[id]/detail/index.tsx
  app/(app)/project/[id]/detail/style.ts
  app/(app)/project/[id]/review/_layout.tsx
  app/(app)/project/[id]/review/create.tsx
  app/(app)/project/[id]/review/index.tsx
  app/(app)/project/_layout.tsx
  app/(app)/project/create.tsx
  app/(app)/project/detail.tsx
  app/(app)/project/index.tsx
  app/(app)/project/review/_layout.tsx
  app/(app)/project/review/complete.tsx
  app/(app)/project/review/create.tsx
  app/(app)/project/review/select.tsx
  app/(app)/project/style.ts
  app/(beforeLogin)/sign-in.tsx
  assets/images/questionnaire/paper.png
  src/__mock__/project/index.ts
  src/apis/auth.ts
  src/apis/member/api.ts
  src/apis/member/type.ts
  src/apis/project/type.ts
  src/apis/questionnaire/api.ts
  src/apis/questionnaire/type.ts
  src/components/common/custom-header/CustomHeader.stories.tsx
  src/components/common/custom-header/index.tsx
  src/components/common/custom-header/style.ts
  src/components/common/custom-layout/index.tsx
  src/components/common/divider/index.tsx
  src/components/common/header/index.tsx
  src/components/common/icon/reset-icon.tsx
  src/components/common/modal/ConfirmModal.stories.tsx
  src/components/common/modal/ConfirmModal.style.ts
  src/components/common/modal/ConfirmModal.tsx
  src/components/project/ProjectDetail/index.tsx
  src/components/project/ProjectItem/index.tsx
  src/components/questionnaire/QuestionnaireCheckList/index.tsx
  src/components/questionnaire/SelectCategoryChipList/index.tsx
  src/components/questionnaire/category-chip/index.tsx
  src/components/questionnaire/category/Category.stories.tsx
  src/components/questionnaire/category/index.tsx
  src/components/review/CreateReviewList/index.tsx
  src/components/sign-in/LoginButton.tsx
  src/config/index.ts
  src/config/stackConfig.ts
  src/constants/navigations.ts
  src/constants/queryKeys.ts
  src/constants/siteUrls.ts
  src/constants/storageKeys.ts
  src/enums/categoryEnum.ts
  src/hooks/queries/useAuth.ts
  src/hooks/queries/useGetCategory.ts
  src/hooks/useTabBarEffect.ts
  src/utils/distributeItems.ts
  src/utils/index.ts
  src/utils/setHeader.ts
Labels: ⚡Feat, 📕Storybook, 🚧Refactor

#85 Feat/#60 리뷰 회의 피드백 반영
  app/(app)/project/detail.tsx
  app/(app)/project/review/create.tsx
  app/(app)/project/review/select.tsx
  src/components/project/ProjectDetail/index.tsx
  src/components/project/ProjectItem/index.tsx
  src/components/review/CreateReviewList/index.tsx
  src/constants/service.ts
Labels: 🚧Refactor

#86 Feat/#60 반복적으로 사용되는 버튼들을 아래에 고정합니다.
  app/(app)/project/detail.tsx
  app/(app)/project/review/complete.tsx
  app/(app)/project/review/create.tsx
  app/(app)/project/review/select.tsx
  src/components/common/custom-layout/index.tsx
  src/components/project/ProjectDetail/ProjectDetail.stories.tsx
  src/components/project/ProjectDetail/index.tsx
  src/components/project/ProjectDetail/style.ts
  src/components/questionnaire/SelectCategoryChipList/index.tsx
Labels: 🚧Refactor
